name: Build Go Executable

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'modern_go_source/**'
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./modern_go_source

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build GUI Executable
      env:
        CGO_ENABLED: 1
      run: go build -v -ldflags="-H windowsgui" -o ServiceTransfer-Modern.exe

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ServiceTransfer-Modern-EXE
        path: ./modern_go_source/ServiceTransfer-Modern.exe
